name: bloc5-prod

services:
  web-prod:
    env_file:
      - .env.prod
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APACHE_CONF: prod.conf
    container_name: videgrenier-web-prod
    ports:
      - "9089:80"
    depends_on:
      - db-prod

  db-prod:
    env_file:
      - .env.prod
    image: mysql:8
    container_name: videgrenier-db-prod
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data_prod:/var/lib/mysql
      - ./sql/import.sql:/docker-entrypoint-initdb.d/import.sql

volumes:
  db_data_prod: